// Hrefs for the basket screens. Typed routes are generated by Metro into .expo/types/router.d.ts;
// until it re-scans after a restart the new paths are not in the union, hence the cast.
import type { Href } from 'expo-router';

export const BASKET_HREF = '/basket' as Href;
export const BASKET_QUOTE_HREF = '/basket/quote' as Href;
export const ALERTS_HREF = '/basket/alerts' as Href;
